import React, { useState, useEffect } from 'react';
import EmployeePayroll from '../../components/EmployeePayroll';
import api from '../../api';

const CashierPayroll = () => {
  const [employee, setEmployee] = useState(null);
  const [payrolls, setPayrolls] = useState([]);
  const [notRegistered, setNotRegistered] = useState(false);

  useEffect(() => {
    const loadData = async () => {
      try {
        const username = localStorage.getItem('username') || localStorage.getItem('employeeId');
        const activeRes = await api.get('/employees/active');
        const staffList = activeRes || [];
        const user = staffList.find(s => s.username === username);
        
        if (user) {
          setEmployee({
            id: user.id,
            name: user.fullName || user.username,
            username: user.username,
            role: user.designation === 'ROLE_CASHIER' ? 'Cashier' : user.designation,
            joiningDate: user.joiningDate
          });
          setNotRegistered(false);
          
          const payrollRes = await api.get(`/payrolls/employee/${user.id}`);
          const userPayrolls = payrollRes || [];
          
          const mappedPayrolls = userPayrolls.map(p => ({
            id: p.id,
            period: `${p.month} ${p.year}`,
            basicSalary: p.basicSalary,
            allowances: 0,
            overtimeHours: 0,
            overtimeRate: 0,
            overtimePay: p.overtimePay,
            bonus: p.bonus,
            deductions: p.deductions,
            netSalary: p.netPay,
            status: p.status,
            generatedAt: p.generatedAt
          }));
          
          setPayrolls(mappedPayrolls.sort((a, b) => new Date(b.generatedAt) - new Date(a.generatedAt)));
        } else {
          setNotRegistered(true);
        }
      } catch (err) {
        console.error('Failed to load payroll:', err);
      }
    };
    
    loadData();
  }, []);

  if (notRegistered) return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-10 text-center max-w-md">
        <div className="w-16 h-16 bg-orange-100 rounded-full flex items-center justify-center mx-auto mb-4">
          <span className="text-2xl">👤</span>
        </div>
        <h2 className="text-xl font-bold text-gray-900 mb-2">Account Not Registered</h2>
        <p className="text-gray-500 text-sm">Your employee profile has not been created by the Owner yet. Please contact your restaurant administrator to add your details in Staff Management.</p>
      </div>
    </div>
  );

  if (employee && payrolls.length === 0) return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-10 text-center max-w-md">
        <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
          <span className="text-2xl">📋</span>
        </div>
        <h2 className="text-xl font-bold text-gray-900 mb-2">No Payslip Available</h2>
        <p className="text-gray-500 text-sm mb-4">Welcome, <strong>{employee.name}</strong>! Your payroll has not been generated by the Owner yet. Once your salary is processed, your payslip will appear here.</p>
        <div className="bg-gray-50 rounded-xl p-4 text-left text-sm text-gray-600 space-y-1">
          <p><strong>Name:</strong> {employee.name}</p>
          <p><strong>Username:</strong> {employee.username}</p>
          <p><strong>Role:</strong> {employee.role || 'Cashier'}</p>
        </div>
      </div>
    </div>
  );

  if (!employee) return (
    <div className="min-h-screen bg-gray-50 flex items-center justify-center">
      <p className="text-gray-500 font-medium">Loading...</p>
    </div>
  );

  const currentPayroll = payrolls[0];

  const earnings = [
    { label: 'Basic Salary', value: `₹ ${currentPayroll.basicSalary}` },
    { label: 'Overtime Pay', value: `₹ ${currentPayroll.overtimePay || 0}` },
    { label: 'Bonuses', value: `₹ ${currentPayroll.bonus || 0}` }
  ];

  const deductions = [
    { label: 'Deductions', value: `₹ ${currentPayroll.deductions}` }
  ];

  const history = payrolls.map(p => ({
    month: p.period,
    netSalary: `₹ ${p.netSalary}`,
    status: p.status
  }));

  const grossSalary = `₹ ${parseFloat(currentPayroll.basicSalary) + parseFloat(currentPayroll.overtimePay || 0) + parseFloat(currentPayroll.bonus || 0)}`;

  return (
    <EmployeePayroll
      employeeName={employee.name}
      employeeId={`CSH-${employee.id}`}
      department="Front Desk"
      role={employee.role || 'Cashier'}
      joiningDate={employee.joiningDate || employee.employmentType || 'N/A'}
      month={currentPayroll.period}
      earnings={earnings}
      deductions={deductions}
      grossSalary={grossSalary}
      netSalary={`₹ ${currentPayroll.netSalary}`}
      payrollHistory={history}
    />
  );
};

export default CashierPayroll;
